"""Default flows seeded for a new brand (Build Spec product direction).

Two flows ship out of the box — the merchant edits these (or adds their own) in the
dashboard. Each customer email is generated by an LLM from the step `prompt`, grounded
in real order context; the branching logic (and discount values) live in the step graph.
"""

from __future__ import annotations

from typing import Any

from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession

from app.models.brand import Brand
from app.models.flow import Flow

_ESCALATE = ["chargeback", "lawyer", "attorney", "fraud", "scam", "dispute", "police"]

WISMO_FLOW: dict[str, Any] = {
    "name": "Where is my order",
    "intent": "wismo",
    "triggers": [
        "where is my order", "where's my order", "wheres my order", "track",
        "tracking", "order status", "status of my order", "haven't received",
        "havent received", "not received", "still waiting", "wismo",
    ],
    "escalate_keywords": _ESCALATE,
    "position": 0,
    "steps": [
        {
            "id": "answer_wismo",
            "type": "message",
            "prompt": (
                "Answer this 'where is my order' question. Use the order status and the "
                "tracking link from CONTEXT, and briefly cite the shipping policy "
                "excerpt. Be warm, concise, and reassuring. Invite them to reply if "
                "anything still looks off after checking the tracking page."
            ),
            "goto": "resolve",
        },
    ],
}

REFUND_FLOW: dict[str, Any] = {
    "name": "Refund request",
    "intent": "refund",
    "triggers": [
        "refund", "money back", "return my order", "want my money",
        "cancel my order", "reimburse", "give me my money",
    ],
    "escalate_keywords": _ESCALATE,
    "position": 1,
    "steps": [
        {
            "id": "offer_50",
            "type": "message",
            "discount_percent": 50,
            "prompt": (
                "The customer wants a refund for their order. Empathise and apologise, "
                "then — instead of refunding — offer them 50% off THIS order to keep it, "
                "using the discount code from CONTEXT. Make the value clear and ask "
                "warmly whether they'd like to keep the order with the discount applied."
            ),
            "branches": [
                {"label": "customer is satisfied / accepts the offer", "goto": "resolve"},
                {"label": "customer is not satisfied / declines the offer", "goto": "offer_80"},
            ],
        },
        {
            "id": "offer_80",
            "type": "message",
            "discount_percent": 80,
            "prompt": (
                "The customer declined the first offer. Acknowledge that, then offer them "
                "80% off their NEXT order (using the discount code from CONTEXT) as a way "
                "to keep them as a customer. Explain the value and ask if that works for "
                "them."
            ),
            "branches": [
                {"label": "customer is satisfied / accepts the offer", "goto": "resolve"},
                {"label": "customer is not satisfied / still wants a refund", "goto": "file_refund"},
            ],
        },
        {
            "id": "file_refund",
            "type": "request_refund_approval",
            "prompt": (
                "The customer still wants a refund. Write an empathetic, reassuring note "
                "letting them know you've sent their refund for the order to the team for "
                "approval and that you'll follow up shortly. Do NOT promise the refund is "
                "complete — it is pending approval."
            ),
        },
    ],
}

DEFAULT_FLOWS = [WISMO_FLOW, REFUND_FLOW]


async def ensure_seed_flows(session: AsyncSession, brand: Brand) -> None:
    existing = (await session.exec(select(Flow).limit(1))).first()
    if existing is not None:
        return
    for spec in DEFAULT_FLOWS:
        session.add(
            Flow(
                brand_id=brand.id,
                name=spec["name"],
                intent=spec["intent"],
                triggers=spec["triggers"],
                escalate_keywords=spec["escalate_keywords"],
                steps=spec["steps"],
                position=spec["position"],
                enabled=True,
            )
        )
    await session.commit()
